version: '3'
services:
  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_APPLICATION_NAME=order-service
    networks:
      - food-delivery-network

  restaurant-service:
    build:
      context: ./stock-service
      dockerfile: Dockerfile
    container_name: restaurant-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_APPLICATION_NAME=restaurant-service
    networks:
      - food-delivery-network

networks:
  food-delivery-network:
    driver: bridge

